apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-ctse-inventory-management
  labels:
        app: docker-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s
  template:
    metadata:
      labels:
        app: docker-k8s
    spec:
      containers:
      - name: docker-k8s
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8085
