name: Docker Build Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ctse-inventory-management
  GKE_CLUSTER: kb-ctse-inventory-management
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: kb-ctse-inventory-management
  IMAGE: github-actions-gke-image
  TAG: 1.0.0
 
jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: {"type": "service_account","project_id": "ctse-inventory-management","private_key_id": "02e939a59664f620e1d84d3880a97fbc68140a6e","private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC96AkFmIdpMdWy\nJjARfqgoXsmMCr95I8OaOOuQgC0oSgpfShs7qRcrgqxkZUyqOK7oeMbew5Qnn/Ay\nwkhyKar3o4T236BkVx++d6dyTx9n0d2DeAkdB/j4OctUf/OIrAKk7Pu5Z1LMHP4A\npVpOXfjVAIXwIZf1Fg8Ni7+LSX8NNah7Xb+a7R4PD3s3NyIJeUTQzBy8DF4qn0zV\nG4BLmYKjX25UK31RH4xhK0rjr/hT+Gz//kVJJ8Ju6MgMKRtLOalHkn05dwVwKgLW\nJx57tdwZY378WRkTkJl56wMkX463ePln+XxK4xm4Q8neSPAJGj36HpQ80bG+bE03\n4wxeOwAvAgMBAAECggEAO1fohdKhsfosNJThXX4uTxs7sSLkrZbC940E861SLy5f\n6mIOe4i94E9fzqmnGORIqAWh45fLUsyUc1Ap8l7Z+bOkB79e8CwXk93xOfPGtRss\nNPqMIoHMx8jLpLatJA7YbrBNgyTqBzWiHBKP00BjUzBsKltdEG3Zu1ppuz120eni\nQWyjKEXuInM6BBktDx6rBxBEezp1hKWWJs/5kmw6BXGs6Was3skOJfMF+p4yafe4\nMNELPyQ4UgRQ2K+zJiWFgbAEPeLFyasO4/5xZhtwEQwOqyrN5Pzo5FsmWD6xAE49\nPPhQ0uwhwXsh9butAJVpFKFp7zRuYw2w/+CPi4l6DQKBgQDjzuyvGvCySM7CBhW1\nRHtUKIb5Z8lwCysikLazGn438VTZ19WIxNs2WbFYF7GrrUYxqTaWxOIsYY0H41Y3\nOVE9wYZVUyEs+ribbMkOOJPiY/zelFVX9IscLJkIimeeotytHF57P9Uh33KNmLjS\nmKfUqgW8wfz0C/RiiGCqm9/EFQKBgQDVaFwugg9alodE8PbPMw+AS6BqJ+rX+8bO\noPHGcWRWh/gWboDKWO3agEonhxIbEqjhLIBERJ1LhbwRMuxn9NLkf7wK00QUl5u1\n40qO4inkZuqKI/UECBrF0bkSmnSgEoUdnD6JH/Fwss/BQGxy3PNeZLKWogvQ8qNE\nYwzpRhcwMwKBgQCnf88BVSKjQ+taN9UgSfEQSRgtK4WuL1gQ+yyKdjFV+sjzv8HO\n5Ud1J+/AoPNPEoFpJEzyAGN4VGW45gvPYQJ+ENwvwobDJroz9YHDRhBeRjx4f8Jc\ngH8EQTpoUDOuLXtqgVBq+N1CIaR9vkwu9HV6ZWUAi/XsjxmqlTHWX/PgnQKBgQCK\n89iRr72vjjOlgAA0CVsefh+E/1i6KQXZpJHIVCyw6vduI6VYG29DxiSCeEAhwJSV\niRQ7XzHL6tf5mt6zEYX/oeweYFED13NbixMQ1dHRFfHA4Ii4h05nX5bRtiAZ2fUy\nwnk1b8cVSlhbzEbQw2zzGT3vNrPa6SHFdXkCqtCOYQKBgEKW5XX/Yrs+Eff55AE4\nm2htAdYAGlepPtpcF0b+9Cu1BcEC90F+O21GMtW3iMonVCH2EacHayNSudetcmSq\nbiSHzgUC6VYzssAkHtMn9supjyokv45gTxQ+jEKwbOZlOuUhOxids3ipb0qy3C4k\n2ijA6p7ToeKucweYyInSX44S\n-----END PRIVATE KEY-----\n","client_email": "625812438774-compute@developer.gserviceaccount.com","client_id": "102735809819625687440","auth_uri": "https://accounts.google.com/o/oauth2/auth","token_uri": "https://oauth2.googleapis.com/token","auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/625812438774-compute%40developer.gserviceaccount.com"}
          project_id: ctse-inventory-management

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
          
      - name: Get GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      
      - name: Build Docker Image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .
          
      - name: Publish Docker Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"
          
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          
      - name: Deploy Image to GKE cluster
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
